services:
  backend:
    container_name: backend
    image: bookreviewer-backend:1.0.0
    ports:
      - 8002:8000

  frontend:
    container_name: frontend
    image: bookreviewer-frontend:1.0.0
    ports:
      - 3002:3000
    depends_on:
      - backend