# Generated by Django 5.0.6 on 2024-07-28 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('SQ', 'Albanian'), ('AR', 'Arabic'), ('HY', 'Armenian'), ('EU', 'Basque'), ('BN', 'Bengali'), ('BG', 'Bulgarian'), ('CA', 'Catalan'), ('KM', 'Cambodian'), ('ZH', 'Chinese (Mandarin)'), ('HR', 'Croatian'), ('CS', 'Czech'), ('DA', 'Danish'), ('NL', 'Dutch'), ('EN', 'English'), ('ET', 'Estonian'), ('FJ', 'Fiji'), ('FI', 'Finnish'), ('FR', 'French'), ('KA', 'Georgian'), ('DE', 'German'), ('EL', 'Greek'), ('GU', 'Gujarati'), ('HE', 'Hebrew'), ('HI', 'Hindi'), ('HU', 'Hungarian'), ('IS', 'Icelandic'), ('ID', 'Indonesian'), ('GA', 'Irish'), ('IT', 'Italian'), ('JA', 'Japanese'), ('JW', 'Javanese'), ('KO', 'Korean'), ('LA', 'Latin'), ('LV', 'Latvian'), ('LT', 'Lithuanian'), ('MK', 'Macedonian'), ('MS', 'Malay'), ('ML', 'Malayalam'), ('MT', 'Maltese'), ('MI', 'Maori'), ('MR', 'Marathi'), ('MN', 'Mongolian'), ('NE', 'Nepali'), ('NO', 'Norwegian'), ('FA', 'Persian'), ('PL', 'Polish'), ('PT', 'Portuguese'), ('PA', 'Punjabi'), ('QU', 'Quechua'), ('RO', 'Romanian'), ('RU', 'Russian'), ('SM', 'Samoan'), ('SR', 'Serbian'), ('SK', 'Slovak'), ('SL', 'Slovenian'), ('ES', 'Spanish'), ('SW', 'Swahili'), ('SV', 'Swedish'), ('TA', 'Tamil'), ('TT', 'Tatar'), ('TE', 'Telugu'), ('TH', 'Thai'), ('BO', 'Tibetan'), ('TO', 'Tonga'), ('TR', 'Turkish'), ('UK', 'Ukrainian'), ('UR', 'Urdu'), ('UZ', 'Uzbek'), ('VI', 'Vietnamese'), ('CY', 'Welsh'), ('XH', 'Xhosa')], default='EN', max_length=2),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('comment', models.TextField()),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
