# Generated by Django 5.0.6 on 2024-11-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_overview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='overview',
            field=models.TextField(null=True),
        ),
    ]
